name: Tests CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Install Test modules
        run: (cd tests && npm install)
      - name: Run tests
        run: npm test
